carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_page, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('adminboard/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review')
]

carts/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation


class Cart(models.Model):
    objects = models.Manager()
    cart_id = models.CharField(max_length=250, blank=True, verbose_name='ID корзины')
    date_added = models.DateField(auto_now_add=True, verbose_name='Дата добавления')

    def __str__(self):
        return self.cart_id

    class Meta:
        verbose_name = 'Корзину'
        verbose_name_plural = 'Корзины'


class CartItem(models.Model):
    objects = models.Manager()
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    variations = models.ManyToManyField(Variation, blank=True, verbose_name='Вариации')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, verbose_name='Корзина')
    quantity = models.IntegerField(verbose_name='Количество')
    is_active = models.BooleanField(default=True, verbose_name='Активно')

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

store/models.py
from django.db import models
from django.db.models import Avg, Count
from django.urls import reverse
from accounts.models import Account
from category.models import Category


class Product(models.Model):
    objects = models.Manager()
    product_name = models.CharField(max_length=200, unique=True, verbose_name='Наименование товара')
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.IntegerField(verbose_name='Цена')
    product_image = models.ImageField(upload_to='photos/products', verbose_name='Фото товара')
    stock = models.IntegerField(verbose_name='Количество на складе')
    is_available = models.BooleanField(default=True, verbose_name='Доступен')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    modified_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменений')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    def get_url(self):
        """
        Get to go to product detail page.
        :return: reverse url for particular product
        """
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def average_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def count_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'цвет'),
    ('size', 'размер'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    variation_category = models.CharField(max_length=100, choices=variation_category_choice, verbose_name='Категория '
                                                                                                          'вариации')
    variation_value = models.CharField(max_length=100, verbose_name='Значение вариации')
    is_active = models.BooleanField(default=True, verbose_name='Активно')
    created_date = models.DateTimeField(auto_now=True, verbose_name='Дата создания')

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

    class Meta:
        verbose_name = 'Вариацию'
        verbose_name_plural = 'Вариации'


class ReviewRating(models.Model):
    objects = models.Manager()

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    user = models.ForeignKey(Account, on_delete=models.CASCADE, verbose_name='Пользователь')
    subject = models.CharField(max_length=100, blank=True, verbose_name='Тема')
    review = models.TextField(max_length=500, blank=True, verbose_name='Отзыв')
    rating = models.FloatField(verbose_name='Рейтинг')
    ip = models.CharField(max_length=20, blank=True, verbose_name='IP адрес')
    status = models.BooleanField(default=True, verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Отзыв и оценку'
        verbose_name_plural = 'Отзывы и оценки'


class ProductGallery(models.Model):
    objects = models.Manager()

    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE, verbose_name='Товар')
    image = models.ImageField(upload_to='store/products', max_length=255, verbose_name='Фото')

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'Галерея товаров'

store/forms.py
from django import forms
from store.models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart, CartItem
from store.models import Product, Variation


def _cart_id(request):
    """
    Get the cart by session_key present in the session
    :param request:
    :return: cart by particular session key
    """
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    """
    Add the particular product to the cart by product id and variations (color, size, etc.)
    if user is authenticated and not.
    :param request:
    :param product_id: id of the product we want to add to the cart
    :return: redirect user to 'cart' page
    """
    current_user = request.user
    product = Product.objects.get(id=product_id)  # get the product
    # If the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            existing_variation_list = [list(item.variations.all()) for item in cart_item]
            item_id_list = [item.id for item in cart_item]

            if product_variation in existing_variation_list:
                # increase the cart item quantity
                item_index = existing_variation_list.index(product_variation)
                item = CartItem.objects.get(product=product, id=item_id_list[item_index])
                item.quantity += 1
                item.save()
            else:
                # create a new cart item
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')

    # If the user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  # get the cart using the cart_id present in the session
        except ObjectDoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
            cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            existing_variation_list = [list(item.variations.all()) for item in cart_item]
            item_id_list = [item.id for item in cart_item]

            if product_variation in existing_variation_list:
                # increase the cart item quantity
                item_index = existing_variation_list.index(product_variation)
                item = CartItem.objects.get(product=product, id=item_id_list[item_index])
                item.quantity += 1
                item.save()
            else:
                # create a new cart item
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    """
    Pressing the minus button decreases the quantity of product by one.
    :param cart_item_id:
    :param request:
    :param product_id:
    :return: render cart page with new quantity
    """
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    """
    Pressing the remove button delete product from cart.
    :param cart_item_id:
    :param request:
    :param product_id:
    :return: render cart page with new list of products
    """
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart_page(request, total=0, quantity=0, cart_items=None, discount=0, grand_total=0):
    """
    This function render 'cart' page and calculate total sum, quantity, discount and grand total sum.
    :param request:
    :param total: Sum without discount in present time
    :param quantity: Product quantity in present time
    :param cart_items: Products in cart
    :param discount: Discount sum
    :param grand_total: Amount including discount
    :return: render 'cart' page
    """
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        # if total < 5000:
        #     discount = round(total * 0.03)
        # else:
        #     discount = round(total * 0.07)
        grand_total = total - discount
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'discount': discount,
        'grand_total': grand_total,
    }

    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None, discount=0, grand_total=0):
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        # if total < 5000:
        #     discount = round(total * 0.03)
        # else:
        #     discount = round(total * 0.07)
        grand_total = total - discount
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'discount': discount,
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
        {% if not cart_items %}
        <div class="text-center">
            <h2>Ваша корзина пуста</h2>
            <br>
            <a href="{% url 'store' %}" class="btn btn-primary">Продолжить покупки</a>
        </div>
        {% else %}
        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                        <tr class="small text-uppercase">
                            <th scope="col">Товар</th>
                            <th scope="col" width="120">Количество</th>
                            <th scope="col" width="120">Цена</th>
                            <th scope="col" class="text-right" width="200"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <figure class="itemside align-items-center">
                                    <div class="aside"><img src="{{ cart_item.product.product_image.url }}" class="img-sm"></div>
                                    <figcaption class="info">
                                        <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                        <p class="text-muted small">
                                            {% if cart_item.variations.all %}
                                            {% for item in cart_item.variations.all %}
                                            {{ item.variation_category|capfirst }} : {{ item.variation_value|capfirst }} <br>
                                            {% endfor %}
                                            {% endif %}
                                        </p>
                                    </figcaption>
                                </figure>
                            </td>
                            <td>
                                <div class="col">
                                    <div class="input-group input-spinner">
                                        <div class="input-group-prepend">
                                            <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light btn-sm btn-quantity" type="button"> <i class="fa fa-minus"></i> </a>
                                        </div>
                                        <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                                        <div class="input-group-append">
                                            <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                                                {% csrf_token %}
                                                {% for item in cart_item.variations.all %}
                                                <input type="hidden" name="{{ item.variation_category|lower }}" value="{{ item.variation_value|capfirst }}">
                                                {% endfor %}
                                                <button class="btn btn-light btn-sm btn-quantity" type="submit"> <i class="fa fa-plus"></i> </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="price-wrap">
                                    <var class="price">{{ cart_item.sub_total }} ₽</var>
                                    <small class="text-muted"> {{ cart_item.product.price }} ₽ за шт. </small>
                                </div>
                            </td>
                            <td class="text-right">
                                <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Вы уверены, что хотите удалить данный товар?')" class="btn btn-outline-secondary btn-sm">Удалить</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </aside>
            <aside class="col-lg-3">
                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Всего:</dt>
                            <dd class="text-right">{{ total }} ₽</dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static 'images/misc/iokassa_color.png' %}" height="26">
                        </p>
                        <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Оформить заказ </a>
                        <a href="{% url 'store' %}" class="btn btn-light btn-block">Продолжить покупки</a>
                    </div>
                </div>
            </aside>
        </div>
        {% endif %}
    </div>
</section>

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
<div class="container">


<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap mainImage">
	   <center><img src="{{ single_product.product_image.url }}"></center>
	</div>

</article>
			<ul class="thumb">
				<li>
					<a href="{{ single_product.product_image.url }}" target="mainImage"><img src="{{ single_product.product_image.url }}" alt="Фото товара"></a>
					{% for i in product_gallery %}
					<a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Фото товара"></a>
					{% endfor %}
				</li>
			</ul>

		</aside>
		<main class="col-md-6 border-left">

<form action="{% url 'add_cart' single_product.id %}" method="POST">
	{% csrf_token %}
	<article class="content-body">

	<h2 class="title">{{ single_product.product_name }}</h2>

	<div class="rating-star">
		<span>
			<i class="fa fa-star{% if single_product.average_review < 0.5 %}-o{% elif single_product.average_review >= 0.5 and single_product.average_review < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.average_review < 1.5 %}-o{% elif single_product.average_review >= 1.5 and single_product.average_review < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.average_review < 2.5 %}-o{% elif single_product.average_review >= 2.5 and single_product.average_review < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.average_review < 3.5 %}-o{% elif single_product.average_review >= 3.5 and single_product.average_review < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if single_product.average_review < 4.5 %}-o{% elif single_product.average_review >= 4.5 and single_product.average_review < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
			<span>{{ single_product.count_review }} отзывов</span>
		</span>
	</div>
	<br>
	<div class="mb-3">
		<var class="price h4">{{ single_product.price }} ₽</var>
	</div>

	<p>{{ single_product.description }}</p>


	<hr>
		<div class="row">
			<div class="item-option-select">
				<h6>Выберите цвет</h6>
				<select name="color" class="form-control" required>
					<option value="" disabled selected >выбор</option>
					{% for i in single_product.variation_set.colors %}
					<option value="{{ i.variation_value | lower}}">{{ i.variation_value | capfirst }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div class="row">
			<div class="item-option-select">
				<h6>Выберите размер</h6>
				<select name="size" class="form-control" required>
					<option value="" disabled selected>выбор</option>
					{% for i in single_product.variation_set.sizes %}
					<option value="{{ i.variation_value | lower}}">{{ i.variation_value | capfirst }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<hr>
		{% if single_product.stock <= 0 %}
		<h5 class="text-danger">Нет в наличии</h5>
		{% else %}
		<button type="submit" class="btn btn-primary"> <span class="text">Купить</span> <i class="fas fa-shopping-cart"></i>  </button>
		{% endif %}

	</article>
	</form>
		</main>
	</div>
</div>

<br>

<div class="row">
			<div class="col-md-9">

	<form action="{% url 'submit_review' single_product.id %}" method="POST">
		{% csrf_token %}
		<h5>Оставьте ваш отзыв</h5>
		<div>
			<!-- Rating stars -->
			<label>Как вы оцените данный товар?</label>
			<br>
			<div class="rate">
				<input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
				<input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
				<input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
				<input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
				<input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
				<input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
				<input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
				<input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
				<input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
				<input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
			</div>
			<br>

			Тема
			<input type="text" class="form-control" name="subject">
			<br>
			Отзыв
			<textarea name="review" rows="4" class="form-control"></textarea>
			<br>
			{% if user.is_authenticated %}
				{% if order_product %}
					<input type="submit" value="Оставить отзыв" class="btn btn-primary">
				{% else %}
				<p>Чтобы оставить отзыв вам необходимо купить данный товар.</p>
				{% endif %}
			{% else %}
			<p>Чтобы оставить отзыв вы должны войти.<span><a href="{% url 'login' %}"> Войти</a></span></p>
			{% endif %}

		</div>
		{% include 'includes/alerts.html' %}
	</form>

	<br>

	<header class="section-heading">
		<h3>Отзывы покупателей</h3>
		<div class="rating-star">
			<span>
				<i class="fa fa-star{% if single_product.average_review < 0.5 %}-o{% elif single_product.average_review >= 0.5 and single_product.average_review < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.average_review < 1.5 %}-o{% elif single_product.average_review >= 1.5 and single_product.average_review < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.average_review < 2.5 %}-o{% elif single_product.average_review >= 2.5 and single_product.average_review < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.average_review < 3.5 %}-o{% elif single_product.average_review >= 3.5 and single_product.average_review < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
				<i class="fa fa-star{% if single_product.average_review < 4.5 %}-o{% elif single_product.average_review >= 4.5 and single_product.average_review < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
				<span>{{ single_product.count_review }} отзывов</span>
			</span>
		</div>
	</header>

	{% for review in reviews %}
	<article class="box mb-3">
		<div class="icontext w-100">
			<div class="text">
				<span class="date text-muted float-md-right">{{ review.updated_at }}</span>
				<h6 class="mb-1">{{ review.user.full_name }}</h6>
				<div class="rating-star">
					<span>
					<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}" aria-hidden="true"></i>
					<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}" aria-hidden="true"></i>
					</span>
				</div>
			</div>
		</div>
		<div class="mt-3">
			<h6>{{ review.subject }}</h6>
			<p>{{ review.review }}</p>
		</div>
	</article>
	{% endfor %}

	</div>
</div>


</div>
</section>

{% endblock %}